web/config/routes.rb
Rails.application.routes.draw do

  resources :alarms
  root 'alarms#index'

end

web/app/models/alarm.rb
class Alarm < ActiveRecord::Base
  def is_weekday
    self.mon && self.tue && self.wed && self.thu && self.fri && !self.sat && !self.sun
  end

  def is_weekend
    !self.mon && !self.tue && !self.wed && !self.thu && !self.fri && self.sat && self.sun
  end

  def repeat
    [:mon, :tue, :wed, :thu, :fri, :sat, :sun].inject('') { |s,d|
      s += ',' + d.to_s if self.send(d)
      s
    }.gsub(/^,/, '')
  end

  def repeat_pretty
    if self.is_weekend
      'Weekend'
    elsif self.is_weekday
      'Weekday'
    else
      self.repeat
    end
  end
end

web/app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]

  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.all
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
    set_default_alarm
  end

  # GET /alarms/1/edit
  def edit
  end

  # POST /alarms
  # POST /alarms.json
  def create
    @alarm = Alarm.new(alarm_params)

    respond_to do |format|
      if @alarm.save
        format.html { redirect_to :action => "index", notice: 'Alarm was successfully created.' }
        format.json { render :show, status: :created, location: @alarm }
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    respond_to do |format|
      if @alarm.update(alarm_params)
        format.html { redirect_to :action => "index", notice: 'Alarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    @alarm.destroy
    respond_to do |format|
      format.html { redirect_to alarms_url, notice: 'Alarm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarm
      @alarm = Alarm.find(params[:id])
    end

    def set_default_alarm
      @alarm.title = "title"
      @alarm.time = Time.now.strftime("%H:%M")
      @alarm.mon = true
      @alarm.tue = true
      @alarm.wed = true
      @alarm.thu = true
      @alarm.fri = true
      @alarm.sat = true
      @alarm.sun = true
      @alarm.snooze = true
      @alarm.enabled = true
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarm_params
      params.require(:alarm).permit(:title, :time, :enabled, :mon, :tue, :wed, :thu, :fri, :sat, :sun, :holiday_off, :sound, :snooze)
    end
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

web/app/helpers/alarms_helper.rb
module AlarmsHelper
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/views/alarms/_alarm_onoff_switch.html.erb
<%= form_for(alarm, remote: true) do |f| %>
  <div class="onoffswitch">
    <% switchId = "enabled_switch_" + alarm.id.to_s %>
    <%= f.check_box :enabled, class: "onoffswitch-checkbox", id: switchId %>
    <label class="onoffswitch-label" for="<%= switchId %>">
        <span class="onoffswitch-inner"></span>
        <span class="onoffswitch-switch"></span>
    </label>
  </div>
<% end %>

web/app/views/alarms/_form.html.erb
<%= form_for(@alarm) do |f| %>
  <% if @alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% @alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="margin-row"></div>

    <div class="clock-row">
      <div class="clock-view">
        <div class="clockpicker">
          <div class="timebox" id="alarm_time_content"><%= @alarm.time %></div>
          <%= f.hidden_field :time, class: "form-control" %>
        </div>
      </div>
      <script type="text/javascript">
        var input = $('.clockpicker').clockpicker({
          placement: 'bottom',
          align: 'right',
          autoclose: true,
          'default': 'now',
          afterDone: function() {
            var time = $("#alarm_time").attr("value");
            $("#alarm_time_content").html(time);
          }
        });

        // Manually toggle to the clockpicker view
        $('#alarm_time_content').click(function(e){
            // Have to stop propagation here
            e.stopPropagation();
            input.clockpicker('show');
        });
      </script>
    </div>

    <div class="std-row">
      <div class="left-label">
          <%= f.label :title %>
        </div>
      <div class="right-field">
        <%= f.text_field :title %>
      </div>
    </div>

    <div class="std-row">
      <div class="left-label">
        <%= f.label :mon %>
      </div>
      <div class="right-field">
        <%= f.check_box :mon %>
      </div>
    </div>

    <div class="std-row">
      <div class="left-label">
        <%= f.label :tue %>
      </div>
      <div class="right-field">
        <%= f.check_box :tue %>
      </div>
    </div>

    <div class="std-row">
      <div class="left-label">
        <%= f.label :wed %>
      </div>
      <div class="right-field">
        <%= f.check_box :wed %>
      </div>
    </div>

    <div class="std-row">
      <div class="left-label">
        <%= f.label :thu %>
      </div>
      <div class="right-field">
        <%= f.check_box :thu %>
      </div>
    </div>

    <div class="std-row">
      <div class="left-label">
        <%= f.label :fri %>
      </div>
      <div class="right-field">
        <%= f.check_box :fri %>
      </div>
    </div>

    <div class="std-row">
      <div class="left-label">
        <%= f.label :sat %>
      </div>
      <div class="right-field">
        <%= f.check_box :sat %>
      </div>
    </div>

    <div class="std-row">
      <div class="left-label">
        <%= f.label :sun %>
      </div>
      <div class="right-field">
        <%= f.check_box :sun %>
      </div>
    </div>

    <div class="std-row">
      <div class="left-label">
        <%= f.label :holiday_off %>
      </div>
      <div class="right-field">
        <%= f.check_box :holiday_off %>
      </div>
    </div>

    <div class="std-row">
      <div class="left-label">
        <%= f.label :sound %>
      </div>
      <div class="right-field">
        <%= f.text_field :sound %>
      </div>
    </div>

    <div class="std-row">
      <div class="left-label">
        <%= f.label :snooze %>
      </div>
      <div class="right-field">
        <%= f.check_box :snooze %>
      </div>
    </div>

    <div class="margin-row"></div>

    <div class="action-row">
      <div class="action-field">
        <%= f.submit value: submit, class: "submit" %>
      </div>
    </div>

  </div>
<% end %>

web/app/views/alarms/edit.html.erb
<%= render 'form', submit: 'Update' %>

<div class="container">
  <div class="action-row">
    <div class="action-field">
      <%= link_to 'Back', alarms_path, class: "back" %>
    </div>
  </div>
  <div class="action-row">
    <div class="action-field">
      <%= link_to 'Delete', @alarm, class: "delete", method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>

web/app/views/alarms/index.html.erb
<% @alarms.each do |alarm| %>
  <div class="alarmview">
    <a href="<%= edit_alarm_path(alarm) %>">
      <div class="info">
        <div class="time">
          <p class="h1"><%= alarm.time %></p>
        </div>
        <div class="opts">
          <p class="small">
            <%= alarm.title %>, <%= alarm.repeat_pretty.gsub(',', ' ') %><br>
            <%= 'Holiday off' if alarm.holiday_off %>
          </p>
        </div>
      </div>
    </a>
    <div class="switch">
      <div class="center-block">
        <%= render 'alarm_onoff_switch', alarm: alarm %>
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    $('.onoffswitch-checkbox').click(function() {
      var form = $(this).closest('form');
      $.ajax({
        type: form.attr('method'),
        url:  form.attr('action'),
        data: form.serialize(),
        dataType: "JSON"
      }).done(function(data){
        console.log('alarm[enabled] update success');
      }).fail(function(data){
        alert('Failure in server communication');
      });
    });
  });
</script>

<br>

<div class="container">
  <div class="margin-row"></div>

  <div class="action-row">
    <div class="action-field">
      <%= link_to '', new_alarm_path, class: 'addition' %>
      <!--<span data-link="<%= new_alarm_path %>" class="addition">-->
    </div>
  </div>
</div>

web/app/views/alarms/new.html.erb
<%= render 'form', submit: 'Create' %>

<div class="container">
  <div class="action-row">
    <div class="action-field">
      <%= link_to 'Back', alarms_path, class: "back" %>
    </div>
  </div>
</div>

web/app/views/alarms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @alarm.title %>
</p>

<p>
  <strong>Time:</strong>
  <%= @alarm.time %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @alarm.enabled %>
</p>

<p>
  <strong>Repeat:</strong>
  <%= @alarm.repeat %>
</p>

<p>
  <strong>Holiday off:</strong>
  <%= @alarm.holiday_off %>
</p>

<p>
  <strong>Sound:</strong>
  <%= @alarm.sound %>
</p>

<p>
  <strong>Snooze:</strong>
  <%= @alarm.snooze %>
</p>

<%= link_to 'Edit', edit_alarm_path(@alarm) %> |
<%= link_to 'Back', alarms_path %>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RPiClock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag('favicon.ico') %>
  <%= favicon_link_tag('apple-touch-icon-144×144-precomposed.png',
                        {:rel => 'apple-touch-icon-precomposed',
                         :sizes => '144x144',
                         :type => 'image/png'}) %>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <meta charset="utf-8">
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand">RPiClock</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="contents">
    <%= yield %>
  </div>

</body>
</html>